lab52/lab52/auth_module/urls.py
from django.urls import path, re_path
from . import views

app_name = 'auth_module'

urlpatterns = [
    re_path(r'^registration/$', views.RegistrationView.as_view(), name='registration'),
    re_path(r'^login/$', views.SignInFormView.as_view(), name='login'),
    re_path(r'^logout/$', views.LogoutFormView.as_view(), name='logout'),
    re_path(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    re_path(r'^edit_profile/$', views.EditProfileView.as_view(), name='edit_profile'),
]

lab52/lab52/lab52/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_module.urls')),
    path('', include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

lab52/lab52/shop/urls.py
from django.urls import path, re_path
from .views import ClientListView, HomePageView, OrderListView, PurchaseListView,StatisticView, about, add_review_view, articles, employee_list, faq, order_create, promocode_list, purchase_create, review_list, vacancy_list

urlpatterns = [
    re_path(r'^clients/$', ClientListView.as_view(), name='clients'),
    re_path(r'^orders/$', OrderListView.as_view(), name='orders'),
    re_path(r'^order/create/(?P<product_id>\d+)/$', order_create, name='create_order'),
    re_path(r'^purchases/$', PurchaseListView.as_view(), name='purchases'),
    re_path(r'^purchase/create/(?P<product_id>\d+)/$', purchase_create, name='create_purchase'),
    re_path(r'^statistic/$', StatisticView.as_view(), name='statistic'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^articles$', articles, name='articles'),
    re_path(r'^faq/$', faq, name='faq'),
    re_path(r'^vacancies/$', vacancy_list, name='vacancies'),
    re_path(r'^employees/$', employee_list, name='employees'),
    re_path(r'^promocodes/$', promocode_list, name='promocodes'),
    re_path(r'^reviews/$', review_list, name='reviews'),
    path('add_review', add_review_view, name='add_review'),
    path('', HomePageView.as_view(), name='home'),
]

lab52/lab52/shop/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Order, Promocode, Purchase, Review
from datetime import date
from django.forms import Select, Textarea

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'text']

        widgets = {
            "rating": Select(choices=[(i, i) for i in range(1, 6)], attrs={'placeholder': 'Choose mark from 1 to 5', 'title': 'Choose mark from 1 to 5'}),
            "text": Textarea(attrs={'placeholder': 'Write here your review'})
        }
        
class OrderForm(forms.ModelForm):    
    promocode = forms.CharField(required=False,widget=forms.TextInput(attrs={'required': False}))  
    class Meta:
        model = Order
        fields = ['quantity', 'pickup_point']

    def clean_promocode(self):
        promocode = self.cleaned_data.get('promocode')
        if promocode:
            promocode_obj = Promocode.objects.filter(code=promocode).first()
            if not promocode_obj:
                raise ValidationError('There is no such promocode')
            else:
                if promocode_obj.is_used:
                    raise ValidationError('Promocode is not valid')
                if promocode_obj.expire_date < date.today():
                    raise ValidationError('Promocode is expired')
        return promocode

class PurchaseForm(forms.ModelForm):    
    class Meta:
        model = Purchase
        fields = ['quantity', 'suplier']

lab52/lab52/shop/views.py
import calendar
from datetime import date, datetime
from io import StringIO
from django.views import View
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest
from django.db.models import Q, Count, Sum
from .models import Client, Employee, Order, Product, ProductType, Promocode, Article, CompanyInfo, FAQ, Purchase, Review, Vacancy
from .forms import OrderForm, PurchaseForm, ReviewForm
from collections import Counter
from statistics import mean, median, mode
from datetime import date, timedelta
from django.utils.timezone import now
from django.contrib.staticfiles.storage import staticfiles_storage
import matplotlib.pyplot as plt
import logging
import requests
import tzlocal

logger = logging.getLogger(__name__)

class HomePageView(View):
    def get(self, request):
        products = Product.objects.all()
        producttypes = ProductType.objects.all()
        is_employee = request.user.groups.filter(name='Employee').exists() if request.user.is_authenticated else False
        is_superuser = request.user.is_superuser if request.user.is_authenticated else False
        price_min = request.GET.get('price_min')
        price_max = request.GET.get('price_max')
        product_type = request.GET.get('producttype')
        search = request.GET.get('search')

        if search:
            products = products.filter(Q(name__icontains=search))
        else:
            if price_min and price_min.isdigit():
                products = products.filter(price__gte=price_min)
            if price_max and price_max.isdigit():
                products = products.filter(price__lte=price_max)
            if product_type:
                products = products.filter(ptype=product_type)
        latest_article = Article.objects.last()
        #catfact = requests.get('https://catfact.ninja/fact').json()
        #text = catfact['fact']
        catfact = ""
        user_timezone = tzlocal.get_localzone()
        current_date = datetime.now(user_timezone)
        current_date_formatted = current_date.date().strftime("%d/%m/%Y")
        calendar_text = calendar.month(
        datetime.now(user_timezone).year,
        datetime.now(user_timezone).month,
        )   
        context = {
            'catfact' : "text",
            'products': products,
            'producttypes': producttypes,
            'is_employee': is_employee,
            'is_superuser': is_superuser,
            'latest_article': latest_article,
            'current_date_formatted': current_date_formatted,
            'calendar_text': calendar_text
        }
        
        return render(request, 'home.html', context)

class ClientListView(ListView):
    model = Client
    template_name = 'clients.html'  
    context_object_name = 'clients'
    ordering = ['last_name']

class OrderListView(ListView):
    model = Order
    template_name = 'orders.html' 
    context_object_name = 'orders'
   
class PurchaseListView(ListView):
    model = Purchase
    template_name = 'purchases.html' 
    context_object_name = 'purchases'

def order_create(request, product_id):
    if request.user.is_authenticated:
        if request.user.groups.filter(name='Client').exists():
            if request.method == 'POST':
                form = OrderForm(request.POST)
                if form.is_valid():
                    order = form.save(commit=False)
                    promocode = form.cleaned_data['promocode']
                    promocode_obj = Promocode.objects.filter(code=promocode).first()
                    if promocode_obj:
                        if promocode_obj.is_used:
                            return HttpResponseBadRequest("Promocode is already used")
                        if promocode_obj.expire_date < date.today():
                            return HttpResponseBadRequest("Promocode is expired")
                        order.promocode = promocode_obj
                        promocode_obj.is_used=True
                        promocode_obj.save()
                    form.instance.client = request.user.client
                    order.client = request.user.client
                    order.product = get_object_or_404(Product, id=product_id)
                    if(order.product.quantity-order.quantity<0):
                        HttpResponseBadRequest("There isn't enough number of products")
                    if promocode_obj is None:
                        discount = 0
                    else:
                        discount = promocode_obj.discount
                    order.price = order.quantity*order.product.price*(100-discount)/100
                    order.product.quantity-=order.quantity
                    order.save()
                    logging.info(f'Order is created, total price {order.price}')
                    return HttpResponse(f'Order is created, total price {order.price}')
            else:
                form = OrderForm()
            return render(request, 'order_create.html', {'form': form})
        else:
            return redirect('/login')
    else:
        logging.warning("Unauthorized user")
        return redirect('/login')
    
def purchase_create(request, product_id):
    if request.user.is_staff or request.user.is_superuser:
        if request.method == 'POST':
            form = PurchaseForm(request.POST)
            if form.is_valid():
                purchase = form.save(commit=False)
                form.instance.suplier = request.user.suplier
                purchase.suplier = request.user.suplierv
                purchase.product = get_object_or_404(Product, id=product_id)
                purchase.price = purchase.quantity*purchase.product.price
                purchase.product+=purchase.quantity
                purchase.product.save()
                purchase.save()
                logging.info(f'Purchase is created, total price {purchase.price}')
                return HttpResponse(f'Purchase is created, total price {purchase.price}')
        else:
            form = PurchaseForm()
        return render(request, 'purchase_create.html', {'form': form})
    else:
        logging.warning("Not staff member")
        return redirect('/login')
    
def all_modes(data):
    counts = Counter(data)
    max_count = max(counts.values())
    modes = [number for number, count in counts.items() if count == max_count]
    return modes  

def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))


class StatisticView(View):
    def get(self, request):
        if not request.user.is_superuser:
            return redirect('login')
        
        orders = Order.objects.all()
        prices = []
        for p in orders:
            prices.append(p.price)
        try:
            average_price = sum(prices)/len(prices)
            sorted_prices = sorted(prices)
            median_price = median(sorted_prices)
            mode_price = mode(prices)
        except:
            average_price = 0
            sorted_prices = 0
            median_price = 0
            mode_price = 0

        date_values = list(Client.objects.values_list('date_of_birth', flat=True))
        age_values = [calculate_age(birth_date) for birth_date in date_values]
        age_avg = mean(age_values)
        age_median = median(age_values)

        popular_product_type = Product.objects.values('ptype').annotate(total=Count('ptype')).order_by('-total').first()
        most_profitable_product_type = Product.objects.values('ptype').annotate(total_profit=Sum('order__price')).order_by('-total_profit').first()
        products_by_orders = Product.objects.annotate(total_orders=Count('order')).order_by('-total_orders')
        monthly_sales = Order.objects.filter(order_date__gte=now()-timedelta(days=30)).values('product__ptype').annotate(total=Sum('quantity'))
        yearly_sales = Order.objects.filter(order_date__gte=now()-timedelta(days=365))
        
        data=Product.objects.values('ptype').annotate(total_profit=Sum('order__price')).order_by('-total_profit')
        product_types = [item['ptype'] for item in data]
        total_profits = [item['total_profit'] for item in data]
        plt.bar(product_types, total_profits)
        plt.xlabel('Product')
        plt.ylabel('Total Orders')
        plt.title('Total Orders by Product')
        file = 'media/images/my_plot.png'
        plt.savefig(file)
        filep='/'+file
        context = {
            'average_price' :average_price,
            'median_price'  :median_price,
            'mode_price' :mode_price,
            'age_avg': age_avg,
            'age_median': age_median,
            'popular_product_type': popular_product_type,
            'most_profitable_product_type': most_profitable_product_type,
            'products_by_orders': products_by_orders,
            'monthly_sales': monthly_sales,
            'yearly_sales': yearly_sales,
            'file':filep
        }
        return render(request, 'statistics.html', context)

def vacancy_list(request):
    vacancies = Vacancy.objects.all()
    return render(request, 'vacancies.html', {'vacancies': vacancies})

def index(request):
    latest_article = Article.objects.last()
    return render(request, 'index.html', {'latest_article': latest_article})

def articles(request):
    articles = Article.objects.all()
    return render(request, 'articles.html',  {'articles': articles})

def about(request):
    company_info = CompanyInfo.objects.last()
    return render(request, 'about.html', {'company_info': company_info})

def faq(request):
    faq_items = FAQ.objects.order_by('-date_added')
    return render(request, 'faq.html', {'faq_items': faq_items})

def promocode_list(request):
    promocodes = Promocode.objects.filter()
    return render(request, 'promocodes.html', {'promocodes': promocodes})

def employee_list(request):
    employees = Employee.objects.all()

lab52/lab52/shop/templates/add_review.html
{% extends "base.html" %}

{% block title %}Create review{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.rating }}
    {{ form.text }}
    <button type="submit">Create</button>
    <span>{{ error }}</span>
</form>
{% endblock %}

lab52/lab52/shop/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Site</title>
</head>
<body>

    <main>
        {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'auth_module:logout' %}">Log out</a>
        {% else %}
        <a href="{% url 'auth_module:registration' %}">Registration</a>
        <a href="{% url 'auth_module:login' %}">Log in</a>
        {% endif %}
        {% block content %}
        {% endblock content %}

    </main>

    <footer>
        <p>© 2024 Site</p>
    </footer>
</body>
</html>
<script>
    let tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (!tz) {
        tz = "UTC"
    }
    document.cookie = "mytz=" + tz + ";path=/";
</script>

lab52/lab52/shop/templates/clients.html
{% extends "base.html" %}

{% block content %}
<h2>Clients</h2>
<form action="{% url 'home' %}" method="get">
    {% csrf_token %}
    <button type="submit">Home</button>
    <ul>
        {% for client in clients %}
        <li>
            <p>{{ client }}</p>
        </li>
        {% endfor %}
    </ul>
    {% endblock %}

lab52/lab52/shop/templates/employees.html
{% extends 'base.html' %}

{% block content %}

<h2>List of employees</h2>

   {% for employee in employees %}

<div>
    <h3>{{ employee.first_name}} {{employee.last_name}}</h3>
    <p>Email: {{ employee.user }}</p>
    <p>Date of birth: {{ employee.date_of_birth }}</p>
</div>

   {% endfor %}

{% endblock %}

lab52/lab52/shop/templates/faq.html
{% extends "base.html" %}

{% block title %}FAQ{% endblock %}

{% block content %}
<section>
    <h1>Frequently asked questions</h1>
    <ul>
        {% for faq_item in faq_items %}
        <li>
            <h3>{{ faq_item.question }}</h3>
            <p>{{ faq_item.answer }}</p>
            <p>Date added: {{ faq_item.date_added }}</p>
        </li>
        {% endfor %}
    </ul>
</section>
{% endblock %}

lab52/lab52/shop/templates/home.html
{% extends "base.html" %}

{% block content %}
<h2>{{ catfact }}</h2>
<div>
    {%load tz%}
    {% get_current_timezone as current_timezone %}
    <p>Current date: {{ current_date_formatted }}</p>
    <p>User time zone: {{ current_timezone }}</p>
    <p><pre>{{calendar_text}}</pre></p>
</div>
    {% if not is_superuser %}
<form action="{% url 'auth_module:profile' %}" method="get">
    {% csrf_token %}
    <button type="submit">Profile</button>
</form>
    {% endif %}
    {% if is_superuser %}
<form action="{% url 'statistic' %}" method="get">
    {% csrf_token %}
    <button type="submit">Statistic</button>
</form>
    {% endif %}
    {% if is_employee or is_superuser %}
<a href="{% url 'clients' %}"><li>Clients</li></a>
<a href="{% url 'orders' %}"><li>Orders</li></a>
<a href="{% url 'purchases' %}"><li>Purchases</li></a>
    {% endif %}

<form action="" method="get">
    <label for="price_min">Price from:</label>
    <input type="number" id="price_min" name="price_min" value="{{ request.GET.price_min }}">
    <label for="price_max">to:</label>
    <input type="number" id="price_max" name="price_max" value="{{ request.GET.price_max }}">
    <label for="producttype">product type:</label>
    <select id="producttype" name="producttype">
        <option value="">All</option>
        {% for producttype in producttypes %}
        <option value="{{ producttype }}" {% if request.GET.producttype == producttype.ptype %}selected{% endif %}>{{ producttype }}</option>
        {% endfor %}
    </select>
    <label for="search">Search (by name):</label>
    <input type="text" id="search" name="search" value="{{ request.GET.search }}">
    <input type="submit" value="Filter">
</form>

    {% for product in products %}
<div>
    <h2>{{ product }}</h2>
    {% if not is_employee and not is_superuser %}
    <form action="{% url 'create_order' product.id %}" method="get">
        {% csrf_token %}
        <input type="submit" value="Order">
    </form>
    {% endif %}
    {% if is_employee or is_superuser %}
    <form action="{% url 'create_purchase' product.id %}" method="get">
        {% csrf_token %}
        <input type="submit" value="Purchase">
    </form>
    {% endif %}
</div>
    {% endfor %}
<article>
    <h3>Last article</h3>
    <h2>{{ latest_article.title }}</h2>
    <p>{{ latest_article.summary }}</p>
    <img src="{{ latest_article.image.url }}" alt="{{ latest_article.title }}" width="400" height="200">
</article>
<a href="{% url 'reviews' %}"><li>Reviews</li></a>
<a href="{% url 'about' %}"><li>About</li></a>
<a href="{% url 'articles' %}"><li>Articles</li></a>
<a href="{% url 'employees' %}"><li>Employees</li></a>
<a href="{% url 'faq' %}"><li>FAQ</li></a>
<a href="{% url 'promocodes' %}"><li>Promocodes</li></a>
<a href="{% url 'vacancies' %}"><li>Vacancies</li></a>
{% endblock %}

lab52/lab52/shop/templates/order_create.html
{% extends 'base.html' %}

{% block content %}
<h2>Create order</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

lab52/lab52/shop/templates/orders.html
{% extends "base.html" %}

{% block content %}
<h2>Orders</h2>
<form action="{% url 'home' %}" method="get">
    {% csrf_token %}
    <button type="submit">Home</button>
</form>
<ul>
    {% for order in orders %}
    <li>
        <h3>{{ order }}</h3>
    </li>
    {% endfor %}
</ul>
{% endblock %}

lab52/lab52/shop/templates/promocodes.html
{% extends 'base.html' %}

{% block content %}
<h2>List of Promocodes</h2>
<ul>
    {% for promocode in promocodes %}
    <li>
        {{ promocode }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

lab52/lab52/shop/templates/purchase_create.html
{% extends 'base.html' %}

{% block content %}
<h2>Create purchase</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

lab52/lab52/shop/templates/purchases.html
{% extends "base.html" %}

{% block content %}
<h2>Purchases</h2>
<form action="{% url 'home' %}" method="get">
    {% csrf_token %}
    <button type="submit">Home</button>
</form>
<ul>
    {% for purchase in purchases %}
    <li>
        <h3>{{ purchase }}</h3>
    </li>
    {% endfor %}
</ul>
{% endblock %}

lab52/lab52/shop/templates/reviews.html
{% extends 'base.html' %}
{% block content %}
  {% if user.client %}
<form action="{% url 'add_review' %}" method="get">
    <button type="submit">Create review</button>
</form>
{% endif %}
<h2>List of Reviews</h2>
  {% for review in reviews %}
<div>
    <h3>Review from: {{ review.client_name }}</h3>
    <p>Text: {{ review.text }}</p>
    <p>Rating: {{ review.rating }}</p>
    <p>Created at: {{ review.created_at }}</p>
</div>
  {% endfor %}
{% endblock %}

lab52/lab52/shop/templates/statistics.html
{% extends "base.html" %}
{% block content %}
<h2>Sales Report</h2>
<p>Total sales: {{ total_sales }}</p>
<p>Average sales: {{ average_price }}</p>
<p>Modes of sales:{{mode_price}}</p>
<p>Median of sales: {{ median_price}}</p>

<p>Average client age: {{ age_avg }}</p>
<p>Median client age: {{ age_median }}</p>
<p>Most popular product type: {{ popular_product_type.ptype }}, num of orders: {{ popular_product_type.total }}</p>
<p>Most popular profitable type: {{ most_profitable_product_type.ptype }}, profit: {{ most_profitable_product_type.total_profit }}</p>
<h3>Products by number of orders:</h3>
<ul>
    {% for product in products_by_orders %}
    <li>{{ product.name }}: {{ product.total_orders }}</li>
    {% endfor %}
</ul>
<img src="{{ file }}" alt="My Plot">
<h3>Monthly sales:</h3>
<ul>
    {% for sale in monthly_sales %}
    <li>{{ sale.product__ptype }}: {{ sale.total }}</li>
    {% endfor %}
</ul>
<h3>Yearly sales:</h3>
<ul>
    {% for sale in yearly_sales %}
    <li>{{ sale }}: {{ sale.price }}</li>
    {% endfor %}
</ul>

{% endblock %}

lab52/lab52/shop/templates/vacancies.html
{% extends 'base.html' %}

{% block content %}
<h2>List of vacancies</h2>
   {% for vacancy in vacancies %}
<div>
    <h3>{{ vacancy.title }}</h3>
    <p>{{ vacancy.description }}</p>
    <p>Creation date: {{ vacancy.creation_date }}</p>
</div>
   {% endfor %}
{% endblock %}