lab52/lab52/auth_module/urls.py
from django.urls import path, re_path
from . import views

app_name = 'auth_module'

urlpatterns = [
    re_path(r'^registration/$', views.RegistrationView.as_view(), name='registration'),
    re_path(r'^login/$', views.SignInFormView.as_view(), name='login'),
    re_path(r'^logout/$', views.LogoutFormView.as_view(), name='logout'),
    re_path(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    re_path(r'^edit_profile/$', views.EditProfileView.as_view(), name='edit_profile'),
]

lab52/lab52/lab52/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_module.urls')),
    path('', include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

lab52/lab52/shop/urls.py
from django.urls import path, re_path
from .views import ClientListView, HomePageView, OrderListView, PurchaseListView,StatisticView, about, add_review_view, articles, employee_list, faq, order_create, promocode_list, purchase_create, review_list, vacancy_list

urlpatterns = [
    re_path(r'^clients/$', ClientListView.as_view(), name='clients'),
    re_path(r'^orders/$', OrderListView.as_view(), name='orders'),
    re_path(r'^order/create/(?P<product_id>\d+)/$', order_create, name='create_order'),
    re_path(r'^purchases/$', PurchaseListView.as_view(), name='purchases'),
    re_path(r'^purchase/create/(?P<product_id>\d+)/$', purchase_create, name='create_purchase'),
    re_path(r'^statistic/$', StatisticView.as_view(), name='statistic'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^articles$', articles, name='articles'),
    re_path(r'^faq/$', faq, name='faq'),
    re_path(r'^vacancies/$', vacancy_list, name='vacancies'),
    re_path(r'^employees/$', employee_list, name='employees'),
    re_path(r'^promocodes/$', promocode_list, name='promocodes'),
    re_path(r'^reviews/$', review_list, name='reviews'),
    path('add_review', add_review_view, name='add_review'),
    path('', HomePageView.as_view(), name='home'),
]

lab52/lab52/auth_module/models.py
from django.db import models

# Create your models here.

lab52/lab52/auth_module/forms.py
from django import forms
from django.core.exceptions import ValidationError
from datetime import date, timedelta
from django.contrib.auth.models import User
from shop.models import Client, Employee

class RegistrationForm(forms.ModelForm):
    login = forms.CharField(widget=forms.TextInput(attrs={'required': True}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'required': True}))

    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'phone', 'date_of_birth']
        widgets = {
            'email': forms.TextInput(attrs={'required': True}),
            'password': forms.TextInput(attrs={'required': True}),
            'first_name': forms.TextInput(attrs={'required': True}),
            'last_name': forms.TextInput(attrs={'required': True}),
            'phone': forms.TextInput(attrs={'required': True, 'pattern': r'\+375 \(\d{2}\) \d{3}-\d{2}-\d{2}'}),
            'date_of_birth': forms.DateInput(attrs={'required': True, 'type': 'date'}),
        }

    def clean_date_of_birth(self):
        dob = self.cleaned_data.get('date_of_birth')
        if dob > date.today():
            raise ValidationError('Date of birth cannot be in the future')
        if dob > date.today() - timedelta(days=18*365):
            raise ValidationError('Client must be at least 18 years old')
        return dob

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('email is already in use')
        else:
            return email

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'phone', 'date_of_birth']

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('date_of_birth'):
            raise ValidationError("Incorrect input")
        if not cleaned_data.get('first_name') or not cleaned_data.get('last_name') or not cleaned_data.get('phone') or not cleaned_data.get('date_of_birth'):
            raise ValidationError("All fields must be filled.")
        if cleaned_data.get('date_of_birth') > date.today() - timedelta(days=18*365):
            raise ValidationError("User must be over 18 years old.")

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'date_of_birth']

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('first_name') or not cleaned_data.get('last_name') or not cleaned_data.get('phone') or not cleaned_data.get('date_of_birth'):
            raise ValidationError("All fields must be filled.")
        if cleaned_data.get('date_of_birth') > date.today() - timedelta(days=18*365):
            raise ValidationError("User must be over 18 years old.")

lab52/lab52/auth_module/views.py
from django.views.generic.edit import FormView
from django.shortcuts import render, redirect
from .forms import ClientForm, EmployeeForm, RegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, login
from django.views import View
from django.contrib.auth.models import User, Group
import logging

logger = logging.getLogger(__name__)

class RegistrationView(View):
    def handle_request(self, request):
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                user = User.objects.create_user(username=form.cleaned_data['login'],email = form.cleaned_data['login'], password=form.cleaned_data['password'], first_name=form.cleaned_data['first_name'], last_name=form.cleaned_data['last_name'])
                client = form.save(commit=False)            
                group = Group.objects.get(name='Client')  
                user.groups.add(group)
                client.user = user
                client.save()
                logging.info("Add new client")
                return redirect('/')
            else:
                logging.info(form.errors)
        else:
            form = RegistrationForm()

        return render(request, 'registration.html', {'form': form})

    get = handle_request
    post = handle_request
    
class LogoutFormView(FormView):
    def get(self, request):
        logout(request)

        return redirect('/')
  
class SignInFormView(FormView):
    form_class = AuthenticationForm
    success_url = '/'
    template_name = 'login.html'

    def get(self, request):
        return render(request, 'login.html', {'form': self.form_class})
    
    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)

        return super(SignInFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(SignInFormView, self).form_invalid(form)

class ProfileView(View):
    def get(self, request):
        if request.user.is_authenticated:
            if request.user.groups.filter(name='Client').exists():
                form = ClientForm(instance=request.user.client)
                template_name = 'client_profile.html'
            elif request.user.groups.filter(name='Employee').exists():
                form = EmployeeForm(instance=request.user.employee)
                template_name = 'employee_profile.html'
            else:
                return redirect('/login')
            return render(request, template_name, {'form': form})
        else:
            return redirect('/login')

class EditProfileView(View):
    def handle_request(self, request):
        if request.user.is_authenticated:
            if request.user.groups.filter(name='Client').exists():
                instance = request.user.client
                FormClass = ClientForm
                template_name = 'client_edit.html'
            elif request.user.groups.filter(name='Employee').exists():
                instance = request.user.employee
                FormClass = EmployeeForm
                template_name = 'employee_edit.html'
            else:
                return redirect('/login')

            if request.method == 'POST':
                form = FormClass(request.POST, instance=instance)
                if form.is_valid():
                    form.save()
                    logging.info("Edit info")
                    return redirect('/profile')
            else:
                form = FormClass(instance=instance)

            return render(request, template_name, {'form': form})
        else:
            return redirect('/login')

    get = handle_request
    post = handle_request

lab52/lab52/auth_module/templates/client_edit.html
{% extends "base.html" %}

{% block content %}
<h1>Edit Client Profile</h1>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

lab52/lab52/auth_module/templates/client_profile.html
{% block content %}
<h1>Client Profile</h1>
<form action="{% url 'home' %}" method="get">
    {% csrf_token %}
    <button type="submit">Home</button>
    {% if user.is_authenticated %}
    <p>Name: {{ user.client.first_name }}</p>
    <p>Surname: {{ user.employee.last_name }}</p>
    <p>Phone: {{ user.client.phone }}</p>
    <p>Date of Birth: {{ user.client.date_of_birth }}</p>
    <a href="{% url 'auth_module:edit_profile' %}">Edit</a>
    {% else %}
    <p>You are not logged in.</p>
    {% endif %}
    {% endblock %}

lab52/lab52/auth_module/templates/employee_edit.html
{% extends "base.html" %}

{% block content %}
<h1>Edit Employee Profile</h1>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

lab52/lab52/auth_module/templates/employee_profile.html
{% extends "base.html" %}

{% block content %}
<h1>Employee Profile</h1>
<form action="{% url 'home' %}" method="get">
    {% csrf_token %}
    <button type="submit">Home</button>
    {% if user.is_authenticated %}
    <p>Name: {{ user.employee.first_name }}</p>
    <p>Surname: {{ user.employee.last_name }}</p>
    <p>Date of Birth: {{ user.employee.date_of_birth }}</p>
    <a href="{% url 'auth_module:edit_profile' %}">Edit</a>
    {% else %}
    <p>You are not logged in.</p>
    {% endif %}
    {% endblock %}

lab52/lab52/auth_module/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Sign in</title>
</head>

<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button class="login_button" type="submit">Log in</button>
        </div>
    </form>

</body>

</html>

lab52/lab52/auth_module/templates/registration.html
<!DOCTYPE html>
<html>

<head>
    <title>Sign up</title>
</head>

<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button class="registration_button" type="submit">Sign up</button>
        </div>
    </form>
</body>

</html>